name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Start build container
      run: echo ${GITHUB_TOKEN} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com;
        docker run -d --name build
        -w $PWD
        -v /home/runner:/home/runner
        -u $(id -u):$(id -g)
        --entrypoint tail
        docker.pkg.github.com/crac/docker-build/image:latest
        -f /dev/null
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - run: bash ./configure
        --disable-warnings-as-errors
        --with-version-pre=crac
        --with-version-build=00
        --with-version-opt=${{ github.run_number }}
        --with-native-debug-symbols=none
      shell: docker exec build bash -e {0}

    - run: |
        make images docs
      shell: docker exec build bash -e {0}

    - name: Bundle
      run: |
        id=$(curl https://api.github.com/repos/crac/criu/releases/tags/release-crac | jq .assets[0].id)
        curl https://api.github.com/repos/crac/criu/releases/assets/$id -LJOH 'Accept: application/octet-stream'
        tar axf criu-dist.tar.gz
        BUNDLENAME=jdk
        mv build/linux-x86_64-server-release/images/jdk $BUNDLENAME
        mv build/linux-x86_64-server-release/images/docs $BUNDLENAME-docs
        cp criu-dist/sbin/criu $BUNDLENAME/lib/criu
        sudo chown root:root $BUNDLENAME/lib/criu
        sudo chmod u+s $BUNDLENAME/lib/criu
        tar -zcf $BUNDLENAME.tar.gz $BUNDLENAME
        tar -zcf $BUNDLENAME-docs.tar.gz $BUNDLENAME-docs

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          jdk.tar.gz
          jdk-docs.tar.gz
